- name: copia del file repository 
  template:
    src: templates/elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: installa ultima versione elastic
  yum:
    name: elasticsearch 
    state: latest

- name: setta il valore di discovery.zen.ping.unicast.hosts
  set_fact:
         el_discovery_zen_ping_unicast_hosts: "{{el_discovery_zen_ping_unicast_hosts + hostvars[groups['master'][item]].ansible_default_ipv4.address}}:9300;"
  with_items:
    - 0
    - 1
    
- name: copia del file di conf di elastic 
  template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    
- name: crea directory per i dati
  file: 
    path: "{{el_path_data}}"
    state: directory
    owner: elasticsearch
    group: elasticsearch

- name: Starta il servizio elasticsearch
  service:
    name: elasticsearch
    state: started    
