- name: copia del file repository 
  template:
    src: templates/elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: installa ultima versione elastic
  yum:
    name: elasticsearch 
    state: latest

- name: copia del file di conf di elastic 
  template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
